
name: m2-actions-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 tests & build'      
    steps:
    - uses: actions/checkout@v2
    - name: 'commit generated magento2 project'
      run: |
        git status
        git config --global user.name 'seyuf'
        git config --global user.email 'contac@madit.fr'
 
